### ISSUE TITLE
Celcius

### ISSUE THREAD

**Issue by samabsalom** [bkpsu/NodeMCU-Home-Automation-Sensor#1]
great project thanks! however, could you help me turn the display into Celsius, please?
Sam

**Comment by bkpsu** [comment]
@samabsalom I just committed a new version of the code, with a new compiler directive (#CELSIUS). I've tried it and it appears to work. Test it and let me know, thanks for submitting the issue!

**Comment by samabsalom** [comment]
Hello, 
Thanks for getting back to me so quick. started fresh with your new code and ran into problems compiling. 
it said
 C:\Users\Sam_A\Desktop\NodeMCU-Home-Automation-Sensor-master\ESP8266-PIR-OLED-Arduino\ESP8266-PIR-OLED-Arduino.ino: In function 'void loop()':

ESP8266-PIR-OLED-Arduino:243: error: too few arguments to function 'void drawDHT(float, float, float, float)'

       drawDHT(h,t,f);

                    ^

C:\Users\Sam_A\Desktop\NodeMCU-Home-Automation-Sensor-master\ESP8266-PIR-OLED-Arduino\ESP8266-PIR-OLED-Arduino.ino:136:6: note: declared here

 void drawDHT(float h, float t, float f, float p)

      ^

Multiple libraries were found for "SSD1306.h"
 Used: C:\Users\Sam_A\Documents\Arduino\libraries\ESP8266_Oled_Driver_for_SSD1306_display
 Not used: C:\Users\Sam_A\Documents\Arduino\libraries\arduino_941869
exit status 1
too few arguments to function 'void drawDHT(float, float, float, float)'

if I removed the ,float p and the ,p from both lines it compiled and uploaded to my board and output a sensible temperature 


Thanks very much! I'm going to try to add OTA to it. I'll let you know how I get on!

**Comment by bkpsu** [comment]
Ah, my mistake! I am working on incorporating a pressure sensor input, and I uploaded half-finished code for that. Line 243 is missing the pressure input.

OTA would be cool and very useful! If you do end up adding it/making it work, l would appreciate if you forked/added a pull request! I will open a new issue for that.
