### ISSUE TITLE
Possible temp offset clac issue?

### ISSUE THREAD

**Issue by testack18** [bkpsu/NodeMCU-Home-Automation-Sensor#13]
Hi BK,

Thanks for sharing your excellent project!
I run into an issue and I'm not sure if it is related to the code or whatever. Please take in consideration that I'm newbie in arduino ide and IOT things so this could be easily my fault.

So the issue is it seems the temp offset is not counted as it should on my device. If I print the value to serial before and after the calculation it shows the exact same value:

```
        Serial.println(String(t));
        t = t + ((5 / 9) * temp_offset);
        Serial.println(String(t));

```

Both has at the moment 27 which is much over as it in reality.
I made some test on the code and it seems int devided by int is int (in this case 0) and 0*temp_offset is 0.

So what about 5.0 / 9.0 ?

Thanks in advance!

**Comment by eugenesilva** [comment]
Same thing with me. The humidity offset works fine... but the temperature offset is not working in Celsious...

**Comment by testack18** [comment]
Try devide float by float: 5.0 / 9.0
That worked for me.

**Comment by eugenesilva** [comment]
Thank you testack18...... I will try it later.

**Comment by eugenesilva** [comment]
It worked testack18... thank you very much.

**Comment by bkpsu** [comment]
Thanks for finding the issue, @testack18 - I committed the fix to the repo, in case others still use the INO.
