### ISSUE TITLE
Add OTA firmware update

### ISSUE THREAD

**Issue by bkpsu** [bkpsu/NodeMCU-Home-Automation-Sensor#2]
It would be great to have the ability to OTA update these sensors wherever they are installed around the house.

**Comment by samabsalom** [comment]
Just sent a PR for this. Hope it works for you too. I tried to do it in a similar way to the rest of your file

Sam

**Comment by bkpsu** [comment]
#5 will fix this.

**Comment by bkpsu** [comment]
Implemented, using @samabsalom  #5
